name: kontakt_unikovka
description: Aplikace na celodenní šifrovačku pro dětský tábor Kontakt

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  confirm_dialog: ^1.0.2
  flutter:
    sdk: flutter

  flutter_sms: ^2.3.3
  get_it: ^7.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  provider: ^6.0.5
  riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/SourceCodePro-Medium.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom assets to your application, add a assets section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "assets" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # assets:
  #   - family: Schyler
  #     assets:
  #       - asset: assets/Schyler-Regular.ttf
  #       - asset: assets/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     assets:
  #       - asset: assets/TrajanPro.ttf
  #       - asset: assets/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding assets from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
